# Generated by Django 2.2.28 on 2023-08-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230827_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='owner_pure_phone',
        ),
    ]
