# Generated by Django 2.2.24 on 2023-08-27 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_auto_20230827_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked',
            field=models.ManyToManyField(related_name='liked_flat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=False, null=True, verbose_name='Новостройка'),
        ),
    ]
