# Generated by Django 2.2.28 on 2023-08-27 16:46
import phonenumbers
from django.db import migrations


def set_general_type_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    all_posts = Flat.objects.all()
    for post in all_posts:
        if post.owner_pure_phone.country_code != 7:
            number = phonenumbers.parse(f'+7{post.owner_pure_phone.national_number}', 'RU')
            if phonenumbers.is_valid_number(number):
                post.owner_pure_phone = number
                post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230827_1852'),
    ]

    operations = [
        migrations.RunPython(set_general_type_number)
    ]
